import type { Metadata } from 'next';
import './globals.css';
import { poppinsFont, robotoFont } from '@/lib/fonts';
import Header from '@/components/header';
import { UserProvider } from './providers/user-provider';
import { auth } from '@/lib/auth';
import { Toaster } from 'sonner';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const user = await auth.getUser();

    return (
        <html lang="en" suppressHydrationWarning>
            <body
                className={`${poppinsFont.className} ${robotoFont.variable} antialiased flex flex-col h-screen`}
            >
                <Toaster richColors />
                <UserProvider userPromise={user!}>
                    <Header user={user!} />
                    {children}
                </UserProvider>
            </body>
        </html>
    );
}
